<?php

declare(strict_types=1);

namespace CloudControl\Shared\Error;

enum ErrorCode: string
{
    case EMAIL_CODE_INVALID = 'CLOUD_EMAIL_CODE_INVALID';
    case EMAIL_CODE_EXPIRED = 'CLOUD_EMAIL_CODE_EXPIRED';
    case EMAIL_DELIVERY_FAILED = 'CLOUD_EMAIL_DELIVERY_FAILED';
    case REGISTRATION_INCOMPLETE = 'CLOUD_REGISTRATION_INCOMPLETE';
    case IDENTITY_NOT_BOUND = 'CLOUD_IDENTITY_NOT_BOUND';
    case IDENTITY_ALREADY_BOUND = 'CLOUD_IDENTITY_ALREADY_BOUND';
    case LAST_IDENTITY_REQUIRED = 'CLOUD_LAST_IDENTITY_REQUIRED';
    case CREDENTIALS_INVALID = 'CLOUD_CREDENTIALS_INVALID';
    case TOTP_REQUIRED = 'CLOUD_TOTP_REQUIRED';
    case TOTP_SETUP_REQUIRED = 'CLOUD_TOTP_SETUP_REQUIRED';
    case TOTP_INVALID = 'CLOUD_TOTP_INVALID';
    case OAUTH_NOT_CONFIGURED = 'CLOUD_OAUTH_NOT_CONFIGURED';
    case OAUTH_STATE_INVALID = 'CLOUD_OAUTH_STATE_INVALID';
    case RATE_LIMITED = 'CLOUD_RATE_LIMITED';
    case INTERNAL_ERROR = 'CLOUD_INTERNAL_ERROR';
}
